### ISSUE TITLE
Warp endpoint returns no results if company's pattern has spaces instead of underscores

### ISSUE THREAD

**Issue by iiiii7d** [Frumple/mrt-api#1]
This affects the following, other companies work fine.

- https://api.minecartrapidtransit.net/api/v1/warps?company=IR
- https://api.minecartrapidtransit.net/api/v1/warps?company=MCR
- https://api.minecartrapidtransit.net/api/v1/warps?company=BR
- https://api.minecartrapidtransit.net/api/v1/warps?company=NSC

looking at https://github.com/Frumple/mrt-api/blob/main/data/companies.yml and https://api.minecartrapidtransit.net/api/v1/companies it seems the culprit is the use of space ` ` in the yml instead of `_` or `\_`? as shown in `#community-issues > Sharing warp data with RapidRoute`

**Comment by Frumple** [comment]
I'm sorry, I'm afraid I'm not following what you're saying here. Could you provide the actual URL request that you tried, and the expected and actual results?

**Comment by iiiii7d** [comment]
The four URLs are

https://api.minecartrapidtransit.net/api/v1/warps?company=IR
https://api.minecartrapidtransit.net/api/v1/warps?company=MCR
https://api.minecartrapidtransit.net/api/v1/warps?company=BR
https://api.minecartrapidtransit.net/api/v1/warps?company=NSC

I expected it to return a non-empty array of warps, but I instead received `[]`

**Comment by Frumple** [comment]
Thanks, I see the problem now.

For https://github.com/Frumple/mrt-api/blob/main/data/companies.yml, I can confirm that the source code version and deployed version are the same, so there are no spaces present in the patterns of the YAML file. 

My guess is something in the pipeline is parsing the `\_` characters and incorrectly converting them to spaces. It could be either: 
- The loading of data from the YAML file into an OrderedMap (https://github.com/Frumple/mrt-api/blob/main/main.go#L110)
- Or the rendering of the OrderedMap values into a RenderList (https://github.com/Frumple/mrt-api/blob/main/companies.go#L37)

**Comment by Frumple** [comment]
This has been fixed in v2.0.0.
